repos:
  - repo: local
    hooks:
      - id: deno-fmt
        name: deno fmt
        entry: deno fmt
        language: system
        files: \.(ts|js|tsx|jsx)$
        pass_filenames: false
      - id: deno-lint
        name: deno lint
        entry: deno lint
        language: system
        files: \.(ts|js|tsx|jsx)$
        pass_filenames: false
