name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test --allow-read --allow-write --allow-net --allow-env --allow-run --no-check

      - name: Test CLI
        run: deno run --allow-read=. --allow-write=. --allow-net --allow-env --allow-run=lms mod.ts --help
